services:
  glueless:
    container_name: glueless
    build:
      context: ./hiddify-core
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    volumes:
      - ./hiddify-core/hiddify-config.json:/hiddify/hiddify-config.json
      - ./hiddify-core/proxy-config.json:/hiddify/proxy-config.json
      - ./logs:/hiddify/logs
    # For accessing services you can forward your ports:
    # ports:
    #   - "9696:9696"
    restart: unless-stopped

  test-client:
    container_name: test-client
    image: alpine:latest
    network_mode: "service:glueless"
    depends_on:
      glueless:
        condition: service_healthy
    command: |
      sh -c "
        apk add --no-cache curl && 
        echo '=== Testing Transparent Proxy ===' &&
        echo 'IP:' && 
        curl -s --max-time 20 ipinfo.io/ip &&
        echo '' &&
        echo 'Location:' && 
        curl -s --max-time 20 ipinfo.io/json | grep -E 'country|city|region'
      "
    profiles:
      - test
